# Generated by Django 4.2.13 on 2024-08-18 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_semestertype_subject_semester_semester_semester_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subject_type_semesters', to='course.semestertype'),
            preserve_default=False,
        ),
    ]
