# Generated by Django 4.2.13 on 2024-08-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_subject_semester_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='semester_type',
        ),
    ]
