# Generated by Django 4.2.13 on 2024-09-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_program_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
