# Generated by Django 4.2.13 on 2024-07-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_teacher_staff'),
        ('app', '0012_remove_department_program_remove_semester_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.semester'),
            preserve_default=False,
        ),
    ]
