# Generated by Django 4.2.13 on 2024-08-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_teacher_staff'),
        ('app', '0014_alter_student_semester_alter_student_session_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_staff', to='course.department'),
        ),
        migrations.AddField(
            model_name='staff',
            name='rank',
            field=models.CharField(choices=[('CH', 'Chairman'), ('AP', 'Associate Professor'), ('AS', 'Assistant Professor'), ('LE', 'Lecturer')], max_length=2, null=True),
        ),
    ]
