# Generated by Django 4.2.13 on 2024-08-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_year_id',
        ),
    ]
