# Generated by Django 4.2.13 on 2024-08-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_staff_password_remove_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_notification',
            name='status',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
