# Generated by Django 4.2.13 on 2024-08-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_semestertype_subject_semester_semester_semester_type'),
        ('app', '0022_staff_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routine',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TeacherSubjectChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='course.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='course.semester')),
                ('semester_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='course.semestertype')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='app.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_choices', to='course.subject')),
            ],
        ),
    ]
