# Generated by Django 4.2.13 on 2024-08-21 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_semester_name_and_more'),
        ('app', '0024_intake_teachersubjectchoice_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='sem_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='course.semester'),
        ),
    ]
