# Generated by Django 4.2.13 on 2024-08-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_staff_credit_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
