# Generated by Django 4.2.13 on 2024-09-07 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_delete_course'),
        ('app', '0030_remove_routine_semester_remove_routine_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='course.semester'),
        ),
    ]
