# Generated by Django 4.2.13 on 2024-08-02 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_teacher_staff'),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='university_name',
        ),
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(choices=[('Mid', 'Mid Exam'), ('Final', 'Final Exam')], default='Mid', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.department'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.semester'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.subject'),
            preserve_default=False,
        ),
    ]
