# Generated by Django 4.2.13 on 2024-08-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_routine_unique_together_teachersubjectchoice'),
        ('question', '0002_remove_exam_course_code_remove_exam_university_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='app.staff'),
            preserve_default=False,
        ),
    ]
