# Generated by Django 4.2.13 on 2024-09-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_delete_course'),
        ('question', '0003_exam_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.department'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='semester_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course.semester'),
        ),
    ]
