# Generated by Django 4.2.13 on 2024-07-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_student_semester'),
        ('course', '0007_remove_teacher_staff'),
        ('seatplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='sem_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatplan',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.student'),
        ),
    ]
