# Generated by Django 4.2.13 on 2024-08-08 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_teacher_department_delete_routine_and_more'),
        ('seatplan', '0002_batch_sem_name_alter_seatplan_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlanRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.program')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seatplan.room')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.semester')),
            ],
        ),
    ]
