# Generated by Django 4.2.13 on 2024-09-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatplan', '0004_remove_seatplanroom_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatplan',
            name='col_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seatplan',
            name='seat_number',
            field=models.IntegerField(default=0),
        ),
    ]
